version: '3.8'

services:
  # API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bpkpd-api
    # restart: unless-stopped
    restart: always
    ports:
      - "127.0.0.1:3333:3333"
    env_file:
      - .env
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3333/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    cpus: "1.25"
    mem_limit: "1536m"
    deploy:
      resources:
        limits:
          cpus: "1.25"
          memory: "1536M"

networks:
  app-network:
  #   driver: bridge

volumes:
  public-data:
  # postgres-data:
  #   driver: local
